CREATE TABLE public.tb_no_generated_value (
                                        id varchar(255) NOT NULL,
                                        create_at timestamp(6) NULL,
                                        CONSTRAINT tb_no_generated_value_pkey PRIMARY KEY (id)
);

CREATE TABLE public.tb_payment_card (
                                        create_at timestamp(6) NULL,
                                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                        cvc varchar(255) NULL,
                                        owner_id varchar(255) NULL,
                                        expiry_date varchar(255) NULL,
                                        "number" varchar(255) NULL,
                                        CONSTRAINT tb_payment_card_number_key UNIQUE (number),
                                        CONSTRAINT tb_payment_card_pkey PRIMARY KEY (id)
);



CREATE TABLE public.tb_payment (
                                   amount int4 NULL,
                                   installment_month int4 NULL,
                                   vat int4 NULL,
                                   create_at timestamp(6) NULL,
                                   id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                   payment_card_id int8 NULL,
                                   CONSTRAINT tb_payment_pkey PRIMARY KEY (id)
);


CREATE TABLE public.tb_cancel (
                                  amount int4 NULL,
                                  vat int4 NULL,
                                  create_at timestamp(6) NULL,
                                  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                  payment_id int8 NULL,
                                  CONSTRAINT tb_cancel_pkey PRIMARY KEY (id),
                                  CONSTRAINT fkey7kchghred9347e6v3fcw3ok FOREIGN KEY (payment_id) REFERENCES public.tb_payment(id)
);


INSERT INTO public.tb_payment_card (create_at, cvc, expiry_date, "number", owner_id) VALUES
                                                                               ('2024-07-21 22:18:21', '806', '1126', '1469911058641541','911014699110'),
                                                                               ('2024-10-04 22:18:21', '374', '0325', '7672986498079427','986476729864'),
                                                                               ('2024-08-16 22:18:21', '731', '0127', '8955477843979745','477889554778'),
                                                                               ('2024-10-09 22:18:21', '612', '0828', '9782438477048327','438497824384'),
                                                                               ('2024-08-05 22:18:21', '113', '0825', '7388272893373635','272873882728'),
                                                                               ('2024-08-01 22:18:21', '538', '1223', '9950939085523308','939099509390'),
                                                                               ('2024-08-12 22:18:21', '489', '0825', '1028489359357816','489310284893'),
                                                                               ('2024-10-01 22:18:21', '435', '0724', '4512495122316136','495145124951'),
                                                                               ('2024-09-15 22:18:21', '457', '0527', '9358910084648623','910093589100'),
                                                                               ('2024-09-03 22:18:21', '873', '0629', '1526954393499777','954315269543');


INSERT INTO public.tb_payment (amount, installment_month, vat, create_at, payment_card_id) VALUES
                                                                                                          (448800, 12, 44800, '2024-09-14 01:20:05', 3),
                                                                                                          (281100, 12, 28100, '2024-11-30 01:20:05', 1),
                                                                                                          (157000, 1, 15700, '2024-09-02 01:20:05', 1),
                                                                                                          (383100, 3, 38300, '2024-11-07 01:20:05', 2),
                                                                                                          (339600, 3, 33900, '2024-11-08 01:20:05', 7),
                                                                                                          (128400, 12, 12800, '2024-11-12 01:20:05', 7),
                                                                                                          (348300, 3, 34800, '2024-09-11 01:20:05', 8),
                                                                                                          (494800, 12, 49400, '2024-10-16 01:20:05', 5),
                                                                                                          (210500, 12, 21000, '2024-11-03 01:20:05', 7),
                                                                                                          (275900, 6, 27500, '2024-09-08 01:20:05', 6);


INSERT INTO public.tb_cancel (amount, vat, create_at, payment_id) VALUES
                                                                      (137 ,13 ,'2024-09-14 01:20:05' ,1 ),
                                                                      (370 ,37 ,'2024-09-14 01:20:05' ,4 ),
                                                                      (296 ,29 ,'2024-09-14 01:20:05' ,3 ),
                                                                      (482 ,48 ,'2024-09-14 01:20:05' ,3 ),
                                                                      (480 ,48 ,'2024-09-14 01:20:05' ,4 ),
                                                                      (453 ,45 ,'2024-09-14 01:20:05' ,8 ),
                                                                      (171 ,17 ,'2024-09-14 01:20:05' ,2 ),
                                                                      (354 ,35 ,'2024-09-14 01:20:05' ,2 ),
                                                                      (183 ,18 ,'2024-09-14 01:20:05' ,9 ),
                                                                      (303 ,30 ,'2024-09-14 01:20:05' ,7 );