server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: jpa-hibernate-tip
  datasource:
    url: jdbc:postgresql://127.0.0.1:7777/docker_postgresql
    username: postgres
    password: 'docker_db_password'
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true


logging:
  level:
    com.exmaple.jpatipsample: TRACE
    org.hibernate.orm.jdbc.bind: TRACE




